// <auto-generated />
using System;
using CodeUnityLabs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeUnityLabs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210135738_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeUnityLabs.Models.Authorizations", b =>
                {
                    b.Property<int>("Authorization_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Authorization_Id"));

                    b.Property<DateTime?>("Expires_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Granted_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Granted_By")
                        .HasColumnType("int");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Authorization_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Authorizations");
                });

            modelBuilder.Entity("CodeUnityLabs.Models.Resource", b =>
                {
                    b.Property<int>("Resource_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Resource_Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Resource_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Resource_Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("CodeUnityLabs.Models.Rezervation", b =>
                {
                    b.Property<int>("Reservation_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Reservation_Id"));

                    b.Property<DateTime>("End_Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<int?>("Equipment_Id")
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<int>("Resource_Id")
                        .HasColumnType("int")
                        .HasColumnName("resource_id");

                    b.Property<int?>("Room_Id")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("Start_Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Reservation_Id");

                    b.HasIndex("Resource_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("CodeUnityLabs.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Type_Id")
                        .HasColumnType("int");

                    b.HasKey("User_Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("User_Type_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeUnityLabs.Models.UserType", b =>
                {
                    b.Property<int>("User_Type_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Type_Id"));

                    b.Property<string>("Type_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Type_Id");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("CodeUnityLabs.Models.WaitingList", b =>
                {
                    b.Property<int>("Waiting_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Waiting_Id"));

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("Requested_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Waiting_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("WaitingList");
                });

            modelBuilder.Entity("CodeUnityLabs.Models.Authorizations", b =>
                {
                    b.HasOne("CodeUnityLabs.Models.User", "User")
                        .WithMany("Authorizations")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeUnityLabs.Models.Rezervation", b =>
                {
                    b.HasOne("CodeUnityLabs.Models.Resource", "Resource")
                        .WithMany("Reservations")
                        .HasForeignKey("Resource_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeUnityLabs.Models.User", "User")
                        .WithMany("Rezervations")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeUnityLabs.Models.User", b =>
                {
                    b.HasOne("CodeUnityLabs.Models.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("User_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("CodeUnityLabs.Models.WaitingList", b =>
                {
                    b.HasOne("CodeUnityLabs.Models.User", "User")
                        .WithMany("WaitingLists")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeUnityLabs.Models.Resource", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("CodeUnityLabs.Models.User", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Rezervations");

                    b.Navigation("WaitingLists");
                });
#pragma warning restore 612, 618
        }
    }
}
